Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 200

Metrics/ClassLength:
  Max: 133

Metrics/AbcSize:
  Max: 25

Naming/UncommunicativeMethodParamName:
  Exclude:
    - './bonus.rb'
    - './button.rb'
    - './save_button.rb'
    - './sprite.rb'

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10